/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.msconnectaccess;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class recursion extends javax.swing.JFrame {

    /**
     * Creates new form recursion
     */
    public recursion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("WOULD YOU LIKE TO ORDER A SNACKS OR DRINKS?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 34, 301, -1));

        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 210, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int orderAgain;
        
        String choice1Str = JOptionPane.showInputDialog(
            null, 
            "[1] = Snacks\n[2] = Drinks\nEnter your choice:"
        );
        
        
        if (choice1Str == null) {
            return;
        }
        
        int choice1 = Integer.parseInt(choice1Str);

        if (choice1 == 1) {
            
            String snacksChoiceStr = JOptionPane.showInputDialog(
                null, 
                "Snacks\n[1] = Piatos [22 pesos]\n[2] = Nova [25 pesos]\nEnter your choice:"
            );
            
            if (snacksChoiceStr == null) return;
            int snackschoi1 = Integer.parseInt(snacksChoiceStr);

            if (snackschoi1 == 1 || snackschoi1 == 2) {
                String itemName = (snackschoi1 == 1) ? "Piatos" : "Nova";
                int price = (snackschoi1 == 1) ? 22 : 25;

                JOptionPane.showMessageDialog(null, "You chose " + itemName + "\nPrice is " + price + " pesos");

                // Quantity
                String quanStr = JOptionPane.showInputDialog(null, "Enter quantity:");
                if (quanStr == null) return;
                int quan1 = Integer.parseInt(quanStr);

                int subtot = quan1 * price;
                JOptionPane.showMessageDialog(null, "Subtotal is: " + subtot + " pesos");

                // Cash Input & Validation Loop
                String cashStr = JOptionPane.showInputDialog(null, "Enter cash:");
                if (cashStr == null) return;
                int cash = Integer.parseInt(cashStr);

                while (cash < subtot) {
                    JOptionPane.showMessageDialog(null, "Insufficient cash!");
                    cashStr = JOptionPane.showInputDialog(null, "Enter cash:");
                    if (cashStr == null) return;
                    cash = Integer.parseInt(cashStr);
                }

                int tot = cash - subtot;
                JOptionPane.showMessageDialog(null, "Your change is: " + tot + " pesos");
            }
        } 
        else if (choice1 == 2) {
            JOptionPane.showMessageDialog(null, "Here are the Choices you have for drinks");
        }
        
        
        int again = JOptionPane.showConfirmDialog(
            null, 
            "Do you want to order again?", 
            "Ordering System",
            JOptionPane.YES_NO_OPTION
        );

        if (again == JOptionPane.YES_OPTION) {
            act(); 
            
        } else {
            JOptionPane.showMessageDialog(null, "Thank you for ordering!");
            exit();
        }
        String choice2Str = JOptionPane.showInputDialog(
            null, 
            "[1] = Snacks\n[2] = Drinks\nEnter your choice:"
        );
        
        
        if (choice2Str == null) {
            return;
        }
        
        int choice2 = Integer.parseInt(choice1Str);

        if (choice2 == 1) {
            
            String snacksChoiceStr = JOptionPane.showInputDialog(
                null, 
                "Snacks\n[1] = Piatos [22 pesos]\n[2] = Nova [25 pesos]\nEnter your choice:"
            );
            
            if (snacksChoiceStr == null) return;
            int snackschoi1 = Integer.parseInt(snacksChoiceStr);

            if (snackschoi1 == 1 || snackschoi1 == 2) {
                String itemName = (snackschoi1 == 1) ? "Piatos" : "Nova";
                int price = (snackschoi1 == 1) ? 22 : 25;

                JOptionPane.showMessageDialog(null, "You chose " + itemName + "\nPrice is " + price + " pesos");

               
                String quanStr = JOptionPane.showInputDialog(null, "Enter quantity:");
                if (quanStr == null) return;
                int quan1 = Integer.parseInt(quanStr);

                int subtot = quan1 * price;
                JOptionPane.showMessageDialog(null, "Subtotal is: " + subtot + " pesos");

                
                String cashStr = JOptionPane.showInputDialog(null, "Enter cash:");
                if (cashStr == null) return;
                int cash = Integer.parseInt(cashStr);

                while (cash < subtot) {
                    JOptionPane.showMessageDialog(null, "Insufficient cash!");
                    cashStr = JOptionPane.showInputDialog(null, "Enter cash:");
                    if (cashStr == null) return;
                    cash = Integer.parseInt(cashStr);
                }

                int tot = cash - subtot;
                JOptionPane.showMessageDialog(null, "Your change is: " + tot + " pesos");
            }
        }          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recursion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void act() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void exit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
