/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.msconnectaccess;

import java.util.Scanner;

/**
 *
 * @author CL2-PC
 */
public class recursionmethod extends javax.swing.JFrame {

    /**
     * Creates new form recursionmethod
     */
    public recursionmethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        snackschoi1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("1 = Snacks");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("2 = Drinks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Enter your Choice:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        snackschoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snackschoi1ActionPerformed(evt);
            }
        });
        getContentPane().add(snackschoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 30, -1));

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    {
        Scanner input = new Scanner(System.in);
        System.out.println("[1] = Snacks");
        System.out.println("[2] = Drinks");
        System.out.println("enter your choice:");
        int choice1 = input.nextInt();
        if(choice1 == 1)
        {
            System.out.println("Snakcs");
            System.out.println("[1] = Piatos [22 pesos]");
            System.out.println("[2] = Nova [25 pesos]");
            System.out.println("enter your choice:");
            int snackschoi1 = input.nextInt();
                if(snackschoi1 == 1)
                {
                    System.out.println("You chosen Piatos ");
                    System.out.println("price is 22 pesos");
                    int piatos = 22;
                    System.out.println("Enter quantity:");
                    int quan1 = input.nextInt();
                    int subtot = quan1 * piatos;
                    System.out.println("Subtotal is : "+subtot);
                    System.out.println("Enter cash:");
                    int cash = input.nextInt();
                    int tot = cash - subtot;
                    while(cash < subtot)
                    {
                    System.out.println("Enter cash:");
                    cash = input.nextInt();
                    tot = cash - subtot;
                    }
                    System.out.println("Your change is :" + tot);
                }
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void snackschoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snackschoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snackschoi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recursionmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recursionmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recursionmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recursionmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recursionmethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField snackschoi1;
    // End of variables declaration//GEN-END:variables
}
