/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.msconnectaccess;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class rockpaperscissor extends javax.swing.JFrame {

    /**
     * Creates new form rockpaperscissor
     */
    public rockpaperscissor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_player2 = new javax.swing.JTextField();
        txt_player1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        player2Health2 = new javax.swing.JLabel();
        player1Health1 = new javax.swing.JLabel();
        healthbar2 = new javax.swing.JTextField();
        healthbar1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Player 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setText("Player 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(txt_player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, -1));
        getContentPane().add(txt_player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, -1));

        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, 40));

        jLabel3.setText("ROCK PAPER SCISSORS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel4.setText("5 HEALTH EACH PLAYER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel5.setText("PAPER = 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        jLabel6.setText("ROCK = 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        jLabel7.setText("SCISSOR = 3");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        player2Health2.setText("HEALTH = ");
        getContentPane().add(player2Health2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        player1Health1.setText("HEALTH = ");
        getContentPane().add(player1Health1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        healthbar2.setText("5");
        getContentPane().add(healthbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 20, -1));

        healthbar1.setText("5");
        getContentPane().add(healthbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(txt_player1.getText());
        int p2 = Integer.parseInt(txt_player2.getText());
        int h1 = Integer.parseInt(healthbar1.getText());
        int h2 = Integer.parseInt(healthbar2.getText());

        
        if(p1 == 1 && p2 == 1)
        {
            JOptionPane.showMessageDialog(jButton1, "Draw", "RPS", JOptionPane.ERROR_MESSAGE);
        }
        if(p1 == 1 && p2 == 2)
        {
            JOptionPane.showMessageDialog(jButton1, "Player 2 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(jButton1, "Player 1 -1 HEALTH.", "RPS", JOptionPane.INFORMATION_MESSAGE);
            int healthbar;
            int deduction = h1 -1;
            healthbar1.setText(""+deduction);
        }
        if(p1 == 1 && p2 == 3)
        {
            JOptionPane.showMessageDialog(jButton1, "Player 1 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(jButton1, "Player 2 -1 HEALTH.", "RPS", JOptionPane.INFORMATION_MESSAGE);
            int deduction = h2 -1;
            healthbar2.setText(""+deduction);
        }

        if(p1 == 2 && p2 == 1)
        {
            JOptionPane.showMessageDialog(jButton1, "Player 1 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(jButton1, "Player 2 -1 HEALTH.", "RPS", JOptionPane.INFORMATION_MESSAGE);
            int deduction = h2 -1;
            healthbar2.setText(""+deduction);
        }
        if(p1 == 2 && p2 == 2)
        {
            JOptionPane.showMessageDialog(jButton1, "Draw", "RPS", JOptionPane.ERROR_MESSAGE);
        }
        if(p1 == 2 && p2 == 3)
        {
            JOptionPane.showMessageDialog(jButton1, "Player 2 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(jButton1, "Player 1 -1 HEALTH.", "RPS", JOptionPane.INFORMATION_MESSAGE);
            int deduction = h1 -1;
            healthbar1.setText(""+deduction);
        }
        if(p1 == 3 && p2 == 1)
        {
            JOptionPane.showMessageDialog(jButton1, "Player 2 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(jButton1, "Player 1 -1 HEALTH.", "RPS", JOptionPane.INFORMATION_MESSAGE);
            int deduction = h1 -1;
            healthbar1.setText(""+deduction);
        }
        if(p1 == 3 && p2 == 2)
        {
            JOptionPane.showMessageDialog(jButton1, "Player 1 Wins", "RPS", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(jButton1, "Player 2 -1 HEALTH.", "RPS", JOptionPane.INFORMATION_MESSAGE);
            int deduction = h2 -1;
            healthbar2.setText(""+deduction);
        }
        if(p1 == 3 && p2 == 3)
        {
            JOptionPane.showMessageDialog(jButton1, "DRAW", "RPS", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rockpaperscissor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rockpaperscissor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rockpaperscissor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rockpaperscissor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rockpaperscissor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField healthbar1;
    private javax.swing.JTextField healthbar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel player1Health1;
    private javax.swing.JLabel player2Health2;
    private javax.swing.JTextField txt_player1;
    private javax.swing.JTextField txt_player2;
    // End of variables declaration//GEN-END:variables
}
